title: Sravya Thoomu # your name (or website title) here
#logo: "/images/girl_logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
   sthoomu@gmail.com
   <br>
   (919)-579-8832
  <br><br>
  Clemson University – Master of Science                                                                   Aug 2008 – Aug 2010
  Thesis specialization in machine learning, optimization and approximation techniques. Worked as research assistant on an automotive research center project. Thesis: Design Decisions Under Uncertainty.
  <br><br>
  <a href="https://www.linkedin.com/in/sravya-t-4474b71b0/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
