title: Sravya # your name (or website title) here
logo: "/images/girl_logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
   Data Scientist with 10+ years of experience in predictive and response modeling, statistical programming, and business intelligence. Worked on wide variety of data sources including digital marketing, banking, finance, automotive, healthcare, real-estate, technology, and agriculture. Adept at predictive modeling, customer segmentation, clustering, time-series forecasting, dashboard development, insights reporting, and key performance metric report creation
  <br><br>
  Ranked in top 10% of undergraduate cohort at XYZ University.
  <br><br>
  <a href="https://www.linkedin.com/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
